"use client";

import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "@/components/shell/app-shell";
import { api, apiBlob } from "@/lib/api";

type Transcript = { id: string; courseClassCode: string; subjectName: string; lecturerName: string; departmentName: string; academicYear: string; semester: string; fileName: string; status: string; createdAt: string; sha256: string; signatureCount: number; rejectionReason: string | null };
type Page = { items: Transcript[]; page: number; size: number; total: number };
type Audit = { id: string; occurredAt: string; actorRole: string; action: string; outcome: string; eventHash: string; metadata: string };
type Signature = { signerType: string; signerName: string | null; certificateSerial: string | null; issuer: string | null; signedAt: string | null; validationStatus: string; validationReason: string | null };
const label = (value: string) => value === "LECTURER_SIGNED" ? ["Chờ duyệt", "waiting"] : value === "DEPT_APPROVED" ? ["Đã duyệt", "approved"] : value === "ARCHIVED" ? ["Đã lưu trữ", "archived"] : ["Bị từ chối", "rejected"];

export default function ExaminationPage() {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(0);
  const [result, setResult] = useState<Page>({ items: [], page: 0, size: 20, total: 0 }); const [selected, setSelected] = useState<Transcript | null>(null);
  const [audit, setAudit] = useState<Audit[]>([]); const [signatures, setSignatures] = useState<Signature[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function search(event?: FormEvent) { event?.preventDefault(); setBusy(true); setError(""); const params = new URLSearchParams({ page: String(page), size: "20" }); if (query.trim()) params.set("q", query.trim()); if (status) params.set("status", status); try { setResult(await api<Page>(`/api/examination/transcripts?${params}`)); } catch (e) { setError(e instanceof Error ? e.message : "Không thể tra cứu hồ sơ."); } finally { setBusy(false); } }
  useEffect(() => { search(); }, [page, status]);
  useEffect(() => { if (!selected) { setAudit([]); setSignatures([]); return; } Promise.all([api<Audit[]>(`/api/audit/transcripts/${selected.id}`), api<Signature[]>(`/api/submissions/${selected.id}/signatures`)]).then(([events, sigs]) => { setAudit(events); setSignatures(sigs); }).catch((e) => setError(e.message)); }, [selected?.id]);
  const pki = signatures.some((item) => ["INVALID", "REVOKED", "EXPIRED"].includes(item.validationStatus)) ? ["Không hợp lệ", "invalid"] : signatures.length > 0 && signatures.every((item) => item.validationStatus === "VALID") ? ["Hợp lệ", "valid"] : ["Chưa xác định", "unknown"];
  async function download(item: Transcript) { try { const blob = await apiBlob(`/api/submissions/${item.id}/file`); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = item.fileName; a.click(); URL.revokeObjectURL(url); } catch (e) { setError(e instanceof Error ? e.message : "Không thể tải file."); } }
  return <AppShell eyebrow="Không gian Khảo thí" title="Tra cứu bảng điểm" description="Tìm hồ sơ, xem lịch sử xử lý và tải bản PDF đã được phân quyền.">
    <section className="grid stats-grid"><div className="stat-card"><div className="stat-top">Hồ sơ tìm thấy <span className="stat-icon">⌕</span></div><div className="stat-value">{result.total}</div><div className="stat-foot">Theo bộ lọc hiện tại</div></div><div className="stat-card"><div className="stat-top">Đang chờ duyệt <span className="stat-icon">◷</span></div><div className="stat-value">{result.items.filter((item) => item.status === "LECTURER_SIGNED").length}</div><div className="stat-foot">Trong trang kết quả</div></div><div className="stat-card"><div className="stat-top">Đã lưu trữ <span className="stat-icon">▣</span></div><div className="stat-value">{result.items.filter((item) => item.status === "ARCHIVED").length}</div><div className="stat-foot">Trong trang kết quả</div></div><div className="stat-card"><div className="stat-top">Trang <span className="stat-icon">#</span></div><div className="stat-value">{result.total ? page + 1 : 0}</div><div className="stat-foot">Tối đa 20 hồ sơ mỗi trang</div></div></section>
    {error && <div className="alert error" role="alert" style={{ marginBottom: 13 }}>{error}</div>}
    <section className="grid two-col">
      <div className="panel"><div className="panel-header"><div><h2 className="panel-title">Danh mục hồ sơ</h2><div className="panel-subtitle">Tra cứu theo mã lớp, môn học, giảng viên hoặc trạng thái</div></div></div>
        <div className="panel-body"><form className="search-row" onSubmit={search}><input className="input" aria-label="Tìm kiếm hồ sơ" placeholder="Mã lớp, môn học, giảng viên…" value={query} onChange={(e) => setQuery(e.target.value)} /><select className="select" aria-label="Lọc trạng thái" value={status} onChange={(e) => { setStatus(e.target.value); setPage(0); }}><option value="">Tất cả trạng thái</option><option value="LECTURER_SIGNED">Chờ duyệt</option><option value="ARCHIVED">Đã lưu trữ</option><option value="REJECTED">Bị từ chối</option></select><button className="button" disabled={busy}>{busy ? "Đang tìm…" : "Tra cứu"}</button></form></div>
        <div className="table-wrap"><table className="table"><thead><tr><th>Lớp / môn học</th><th>Khoa</th><th>Giảng viên</th><th>Trạng thái</th><th></th></tr></thead><tbody>{result.items.map((item) => { const [text, cls] = label(item.status); return <tr key={item.id}><td><button className="file-link" style={{ border: 0, background: "none", padding: 0 }} onClick={() => setSelected(item)}>{item.courseClassCode}</button><div className="table-secondary">{item.subjectName} · {item.semester}</div></td><td>{item.departmentName}</td><td>{item.lecturerName}</td><td><span className={`status ${cls}`}>{text}</span></td><td><button className="button secondary small" onClick={() => download(item)}>Tải PDF</button></td></tr>; })}</tbody></table>{result.items.length === 0 && <div className="empty-state"><div className="empty-icon">⌕</div>{busy ? "Đang tìm hồ sơ…" : "Không có hồ sơ phù hợp."}</div>}</div>
        <div className="pagination"><span>Hiển thị {result.items.length ? page * result.size + 1 : 0}–{Math.min((page + 1) * result.size, result.total)} / {result.total}</span><div className="button-row"><button className="button secondary small" disabled={page === 0} onClick={() => setPage((p) => Math.max(0, p - 1))}>Trước</button><button className="button secondary small" disabled={(page + 1) * result.size >= result.total} onClick={() => setPage((p) => p + 1)}>Tiếp</button></div></div>
      </div>
      <div className="panel"><div className="panel-header"><div><h2 className="panel-title">Dấu vết hồ sơ</h2><div className="panel-subtitle">Mốc thời gian lấy từ audit phía máy chủ</div></div></div>
        {selected ? <div className="panel-body section-stack"><div className="detail-list"><div className="detail-line"><span>Hồ sơ</span><strong>{selected.courseClassCode} · {selected.subjectName}</strong></div><div className="detail-line"><span>Chữ ký ghi nhận</span><strong>{selected.signatureCount}</strong></div><div className="detail-line"><span>SHA-256</span><strong className="token-badge">{selected.sha256.slice(0, 18)}…</strong></div><div className="detail-line"><span>Kết quả PKI</span><strong><span className={`status ${pki[1]}`}>{pki[0]}</span></strong></div></div><div><div className="panel-title" style={{ marginBottom: 9 }}>Chứng thư ký</div>{signatures.length ? signatures.map((signature, index) => <div className="detail-line" key={index}><span>{signature.signerType === "LECTURER" ? "Giảng viên" : "Trưởng khoa"}</span><strong>{signature.signerName ?? "Không đọc được tên"} · {signature.validationStatus}{signature.validationReason ? ` (${signature.validationReason})` : ""}</strong></div>) : <div className="hint">Chưa có chữ ký hoặc chưa lưu được metadata chữ ký.</div>}</div><div className="timeline">{audit.length ? audit.map((event) => <div className="timeline-item" key={event.id}><div className="timeline-action">{event.action.replaceAll("_", " ")} · {event.outcome}</div><div className="timeline-time">{new Date(event.occurredAt).toLocaleString("vi-VN")} · {event.actorRole}</div><div className="timeline-time">Hash sự kiện: {event.eventHash.slice(0, 18)}…</div></div>) : <div className="empty-state">Chưa có sự kiện kiểm toán.</div>}</div><button className="button secondary" onClick={() => setSelected(null)}>Đóng chi tiết</button></div> : <div className="empty-state"><div className="empty-icon">⌕</div>Chọn hồ sơ trong bảng để xem lịch sử.</div>}
      </div>
    </section>
  </AppShell>;
}
